GET http://localhost:8000/api/v1/tags HTTP/1.1
Content-Type: application/json
Authorization:Bearer 1|ROYMJOAJtTgQXX5872rDIwH9SFYIPg7NmQQPfF6M

# POST http://localhost:8000/api/v1/login HTTP/1.1
# Content-Type: application/json

# {
#     "email": "test@gmail.com",
#     "password": "password"
# }